# Site settings
title: "Gilles Bertaux : Co-founder/CEO Rumble"
email: hello@gillesbertaux.com
description: "My name is Gilles Bertaux. I am one of the co-founder of Rumble. Striving to make webinars smarter. Formerly Product Designer at TOTEMS and Growth at Mention."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gillesbertaux.com" # the base hostname & protocol for your site
twitter_username: gillesbertaux
github_username:  gillesbertaux

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: :compressed
gems:
  - octopress-minify-html
  - octopress-autoprefixer
minify_html: true
