---
title: 'Gilles Bertaux : Co-founder/CEO Livestorm'
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@gillesbertaux.com
description: My name is Gilles Bertaux. I am the co-founder and CEO of Livestorm.
  Striving to make webinars smarter. Formerly Product Designer at TOTEMS and Growth
  at Mention.
baseurl: ''
url: http://gillesbertaux.com
twitter_username: gillesbertaux
github_username: gillesbertaux
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
- octopress-autoprefixer
- jekyll-assets
- jekyll-coffeescript
