# Site settings
title: "Gilles Bertaux : Product Design + Growth"
email: hello@gillesbertaux.com
description: "Hi there, my name is Gilles Bertaux. Formerly Product Designer at TOTEMS, now Growth at Mention. I do: Product Management, Product Design & Growth."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gillesbertaux.com" # the base hostname & protocol for your site
twitter_username: gillesbertaux
github_username:  gillesbertaux

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: :compressed
gems:
  - octopress-minify-html
minify_html: true
